#!/bin/sh
mv $1 yyyyy.c
if [ -x /usr/bin/cpp ] ; then
  if [ `uname` = "Linux" ] ; then
    FLAG=-traditional
    VERS=`gcc -dumpfullversion | \
    sed -e 's/\([0-9]*\.[0-9]*\)\.[0-9]*/\1/' \
	-e 's/\.\([0-9][0-9]\)/\1/' \
	-e 's/\.\([0-9]\)/0\1/'`
    if [ $VERS -gt 408 ] ; then
      FLAG="$FLAG -ffreestanding"
    fi
  fi
  /usr/bin/cpp -P -C $FLAG yyyyy.c > $1		# Linux
else
  if [ -x /usr/ccs/lib/cpp ] ; then
    /usr/ccs/lib/cpp -P -C yyyyy.c > $1		# Solaris
  else
    cc -E -P -C yyyyy.c > $1
  fi
fi
rm -f yyyyy.c
