LIB		= $(HOME)/lib
REUSE		= ../../../reuse
MLIB		= $(REUSE)/src
CFLAGS		= -I $(LIB)/include
CPPFLAGS	= -I $(LIB)/cplusinc
CC		= cc -g # -DDebug
ADA		= ADA_INCLUDE_PATH=$(REUSE)/ada gcc -c -g

CT		= $(HOME)

DIFF		= diff

# The rest is only of interest to the Java version.
# Comment/Uncomment lines as required by your environment.

# Class path seperator
# Windows
# CPS=;
# Unix
CPS=:

# Location of the JDK
# JDK		= /usr/share/kaffe/Klasses.jar
# JDK		= /usr/local/jdk1.2.2
# JDK		= /usr/lib/jdk1.1.8
# JDK		= /usr/lib/SunJava2-1.4.2
# JDK		= /usr/lib/jvm/java-1.4.2-gcj-1.4.2.0
# JDK		= /usr/lib/jvm/java-1.5.0-sun-1.5.0_update8
# JDK		= /usr/lib64/jvm/java-1.6.0-openjdk-1.6.0
JDK		= /home/local/lib64/jdk1.8.0_92

# Set JDK1 for compilers without a separate -bootclass argument, and
# which do not search the JDK classes automatically (e.g. IBM's jikes)
# Note the directory separator at the start
#
# JDK1		= $(CPS)$(JDK)/lib/classes.zip
JDK1		= $(CPS)$(JDK)/jre/lib/rt.jar
# jikes on Red Hat linux using the Kaffe JDK, or the Kaffe compiler
# JDK1		= $(CPS)$(JDK)/Klasses.jar

# Includes for compiling C code called via JNI
# 1.2.2 on Linux
# JDK_JNI		= -I $(JDK)/include -I $(JDK)/include/linux
# 1.1.7 on Linux
# JDK_JNI		= -I $(JDK)/include -I $(JDK)/include/genunix
# 1.1.8 on Linux
JDK_JNI		= -I $(JDK)/include -I $(JDK)/include/linux

# This is for compiling reuse only.  See reuse/java/Makefile.
# Classpath for javadoc.  Because we supply a resource file to change some
# of the text in the generated HTML, we need the path to find javadoc.
# See also the 'doc' target.
#
JAVADOCPATH	= $(JDK)/lib/tools.jar

# Java compiler to be used, with any compiler specific options
#
# Sun javac
JAVAC		= javac -deprecation
#
# IBM Jikes (this needs JDK1 to be set as well)
# JAVAC		= jikes
#
# kaffe (this needs JDK1 to be set as well)
# JAVAC		= javac

# Command to run a java program
JAVA		= java

# Jar utility to be used, with options
#
# Standard platform, e.g. Sun
JAR		= jar cf

# the rest of these should not need to be changed: they are common
# combinations of the above items.

# class path for applications
CLASSPATH	= .$(CPS)$(LIB)/reuse.jar$(JDK1)

