.TH l2r 1 "" GMD
.SH NAME
l2r - transform LEX specifications to REX specifications
.SH SYNOPSIS
l2r
.SH DESCRIPTION
L2r transforms a LEX specification to a REX specification.
Input is read from stdin, output is written to stdout.
.SH RESTRICIONS
Some LEX features are not supported by REX.
.SH SEE ALSO
lex (1), rex (1)
