#define DEFINITION_SysError

extern BOOLEAN Zp6VmlNKK_0 ARGS ((INTEGER Z116));
extern void Zp6VmlNKK_1 ARGS ((INTEGER Z116, CARDINAL Z118, CARDINAL Z119, ADDRESS Z120));
extern void Zp6VmlNKK_2 ARGS ((INTEGER Z116, CARDINAL Z118));
extern void BEGIN_SysError ARGS ((void));
