.TH BNF 1 1 "" "CoCoLab Karlsruhe"
.SH NAME
bnf \- convert a grammar from EBNF to BNF
.SH SYNOPSIS
bnf [-c|-m|-eiffel] [-h][-l][-g] <file>
.SH DESCRIPTION
Bnf translates a context-free grammar in EBNF into an equivalent grammar
in BNF, which is written to standard output.
The result can be used as input for the parser generator lalr.
.SH OPTIONS
.IP c 
the target language is C
.IP m 
the target language is Modula-2 (default)
.IP eiffel 
the target language is Eiffel
.IP h
print further help information
.IP l 
print complete (error) listing
.IP g
generate # line directives
.SH SEE\ ALSO
J. Grosch, B. Vielsack: "The Parser Generators Lalr and Ell",
GMD Forschungsstelle an der Universitaet Karlsruhe,
Compiler Generation Report No. 8, 1991
