
all:
	cd modula	&& $(MAKE)
	cd context	&& $(MAKE)
	cd interfaces	&& $(MAKE)
	cd small	&& $(MAKE)

clean:
	cd modula	&& $(MAKE) clean
	cd context	&& $(MAKE) clean
	cd interfaces	&& $(MAKE) clean
	cd small	&& $(MAKE) clean
