LIB	= $(HOME)/lib

all:
	cd R		&& $(MAKE) LIB=$(LIB)
	cd _		&& $(MAKE) LIB=$(LIB)
	cd eq		&& $(MAKE) LIB=$(LIB)
	cd gp		&& $(MAKE) LIB=$(LIB)
	cd k		&& $(MAKE) LIB=$(LIB)
	cd o		&& $(MAKE) LIB=$(LIB)
	cd q		&& $(MAKE) LIB=$(LIB)
	cd rw		&& $(MAKE) LIB=$(LIB)
	cd tb		&& $(MAKE) LIB=$(LIB)
	cd y		&& $(MAKE) LIB=$(LIB)
	cd large	&& $(MAKE) LIB=$(LIB)
	cd mse		&& $(MAKE) LIB=$(LIB)

clean:
	cd R		&& $(MAKE) clean
	cd _		&& $(MAKE) clean
	cd eq		&& $(MAKE) clean
	cd gp		&& $(MAKE) clean
	cd k		&& $(MAKE) clean
	cd o		&& $(MAKE) clean
	cd q		&& $(MAKE) clean
	cd rw		&& $(MAKE) clean
	cd tb		&& $(MAKE) clean
	cd y		&& $(MAKE) clean
	cd large	&& $(MAKE) clean
	cd mse		&& $(MAKE) clean

