LIB	= $(HOME)/lib

test:
	cd ffaba-c	; $(MAKE) LIB=$(LIB)
	cd ffaba-m	; $(MAKE) LIB=$(LIB)
	cd minilax-j	; $(MAKE) LIB=$(LIB)
	cd mse-j	; $(MAKE) LIB=$(LIB)

clean:
	cd ffaba-c	; $(MAKE) clean
	cd ffaba-m	; $(MAKE) clean
	cd minilax-j	; $(MAKE) clean
	cd mse-j	; $(MAKE) clean

