#define DEFINITION_General

typedef struct General_1 {
CHAR C_0_char;
LONGREAL Y1;
} ZdaDDAD7_0;
#define ZdaDDAD7_1	(sizeof (ZdaDDAD7_0) - sizeof (LONGREAL))
extern BITSET ZdaDDAD7_2;
extern INTEGER ZdaDDAD7_3 ARGS ((INTEGER Z120, INTEGER Z121));
extern INTEGER ZdaDDAD7_4 ARGS ((INTEGER Z120, INTEGER Z121));
extern LONGCARD ZdaDDAD7_5 ARGS ((LONGCARD Z120, LONGCARD Z121));
extern LONGCARD ZdaDDAD7_6 ARGS ((LONGCARD Z120, LONGCARD Z121));
extern CARDINAL ZdaDDAD7_7 ARGS ((LONGCARD Z126));
extern LONGCARD ZdaDDAD7_8 ARGS ((CARDINAL Z126));
extern CARDINAL ZdaDDAD7_9 ARGS ((LONGINT Z126));
extern CARDINAL ZdaDDAD7_10 ARGS ((LONGINT Z126));
extern REAL ZdaDDAD7_11 ARGS ((INTEGER Z126));
extern void BEGIN_General ARGS ((void));
